server: # webserver port(default : 8080, 0으로 하면 random port)
  port: 5555

spring:
  # 데이터베이스 연결 정보
  datasource:
    # mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/g2mDB?serverTimezone=UTC&characterEncoding=UTF-8
    username: g2m
    password: g2m1!g2m2@
    # 커넥션 풀 (HikariCP) 설정 (선택)
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 20000
      max-lifetime: 1800000

springdoc:
  swagger-ui:
    csrf:
      enabled: true

mybatis:
  # mapper-locations: file:src/main/java/com/bnz/stepmon/**/*Query.xml # xml파일을 src/main/java 하위에 두고 싶을때...(비추천)
  mapper-locations: classpath:com/bnz/stepmon/sql/*Query.xml # src/main/resources 하위에 놓는경우(default)
  configuration:
    map-underscore-to-camel-case: true #카멜 케이스 자동 변환 (db_column -> dbColumn)
    call-setters-on-nulls: true #쿼리 결과가 null일 때 setter 호출 여부
    jdbc-type-for-null: NULL

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN:777630358:AAElntpm3KBBIshGfBMqL_65VYKqbX3Xn-I}
    username: bzNotiTestBot
  chat:
    id: -1001163615391 # @bzSignalCH_TEST 채널

# Apple 앱 푸시
apns:
  team-id: "6N5396RU93" #Apple # Developer 계정 Team ID
  key-id: "M48CNFDVZQ" # AuthKey_XXXX.p8 의 XXXX 부분
  p8-path: "keys/AuthKey_M48CNFDVZQ.p8"
  topic: "com.bnz.StepMon"
  use-sandbox: true  # 개발/디버그: true, TestFlight/배포: false

  profiles:
    active: local  # 기본적으로 로컬 환경을 사용하도록 설정
